kind: Secret
apiVersion: v1
metadata:
  name: mnist-s3-creds
  namespace: feast
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: mnist-s3
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: default
  AWS_S3_BUCKET: feast
  AWS_S3_ENDPOINT: http://minio-service.feast.svc.cluster.local:9000
  AWS_SECRET_ACCESS_KEY: minio123
type: Opaque
